name: SSH into EC2 instance on push and merge to main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: aws-access-key-id:${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key:${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region:us-east-1
  continuous-deployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:us-east-1
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name github_dep \
            --deployment-group-name github_dep_group \
            --deployment-config-name CodeDeployDefault.OneAtTime \
            --github-location repository=${{ GPS-NAJO/Webpage }},commitId=${{ github.sha }}
