name: SSH into EC2 instance on push and merge to main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Connect to EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_IP_ADDRESS }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo cd /home/ubuntu/Webpage/
          sudo git pull
          sudo npm install
          PID=$(sudo pgrep -f "node bin/www")
          if [ -n "$PID" ]; then
            sudo kill "$PID"
          fi
          sudo nohup node bin/www &
